### ISSUE TITLE
Crash with java.lang.IllegalArgumentException: Unique transitionNames are required for all sharedElements

### ISSUE THREAD

**Issue by Werder630** [material-components/material-components-android-motion-codelab#4] opened 2020-08-15 19:01 UTC
Branch **complete**
On click on MaterialCardView of  HomeFragment#onEmailClicked get crash:
```
    java.lang.IllegalArgumentException: Unique transitionNames are required for all sharedElements
        at androidx.fragment.app.FragmentTransaction.addSharedElement(FragmentTransaction.java:595)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:212)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:58)
        at androidx.navigation.NavController.navigate(NavController.java:933)
        at androidx.navigation.NavController.navigate(NavController.java:867)
        at androidx.navigation.NavController.navigate(NavController.java:1006)
        at com.materialstudies.reply.ui.home.HomeFragment.onEmailClicked(HomeFragment.kt:117)
        at com.materialstudies.reply.databinding.EmailItemLayoutBindingImpl._internalCallbackOnClick(EmailItemLayoutBindingImpl.java:219)
        at com.materialstudies.reply.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by IgnacioGarcia198** [comment] 2020-08-17 08:19
Also got same issue on branch develop after step 4 of the codelab. The change made in HomeFragment.onEmailClicked() on this step seems to trigger the issue.

**Comment by Werder630** [comment] 2020-08-17 08:58
It seems `android:transitionName="@{@string/email_card_transition_name(email.id)}"` has not correct value

**Comment by dsn5ft** [comment] 2020-08-17 13:26
@Werder630 @IgnacioGarcia198 thanks for trying out the codelab!

When I check out the `complete` branch, run the app, and click on an email, the transition runs successfully and I don't see the crash. Same thing happens if I start from `develop` and add in the transition names, the navigate call with `FragmentNavigatorExtras`, and the `MaterialContainerTransform` `sharedElementEnterTransition`.

Can you make sure that the `android:transitionName="@{@string/email_card_transition_name(email.id)}"` is set on the `MaterialCardView` in `email_item_layout.xml`, as opposed to the `MaterialCardView` in `fragment_email.xml`? That's the important part for ensuring uniqueness.

Also, if you can fork the codelab repo and push your local changes to a branch, I can take a look to see if there's an issue.

**Comment by IgnacioGarcia198** [comment] 2020-08-17 13:36
It seems like assigning the email variable to the binding in the is not updating the property in the CardView itself.
One way of fixing it is assigning the transitionName directly in EmailViewHolder.bind:
`binding.cardView.transitionName = itemView.context.getString(R.string.email_card_transition_name, email.id)`

**Comment by dsn5ft** [comment] 2020-08-17 13:40
@IgnacioGarcia198 would you be able to push your changes that reproduce the crash to a branch?

**Comment by IgnacioGarcia198** [comment] 2020-08-17 13:45
@dsn5ft Of course. How should we name it, issue#4Reproduction?

**Comment by dsn5ft** [comment] 2020-08-17 13:46
@IgnacioGarcia198 thanks, sounds good to me!

**Comment by IgnacioGarcia198** [comment] 2020-08-17 14:12
@dsn5ft I created the pull request from my fork. Although mysteriously enough, now the issue is not happening anymore on any of the branches.

**Comment by dsn5ft** [comment] 2020-08-17 14:19
Hmm yeah I don't see anything wrong with your code. Maybe @Werder630 will be able to reproduce it and create a branch.

**Comment by Werder630** [comment] 2020-08-17 14:27
i haven't changed anything in codelabs, just cloned repo and checkout branch "complete", next launch app and click on card. App crashes with my stack

**Comment by dsn5ft** [comment] 2020-08-17 14:37
Gotcha. By any chance did you happen to upgrade any Gradle versions with Android Studio's suggestion popup? Can you do a `git status` to make sure that you don't have any local changes at all?

Also, does the crash happen when clicking on all of the cards? Or just some of them?

**Comment by IgnacioGarcia198** [comment] 2020-08-17 14:50
@dsn5ft I made no changes at all in Gradle, etc. As far as I know it looks like an issue that only happens under certain circumstances, probably something to do with the proper working of DataBinding in certain circumstances. For example, at the time I was getting the crash, text related to the DataBinding layouts was in red, not sure if it could have something to do.
I think it was happening when clicking on any card.
I checked my status, I have no local changes, after I cleared app data and uninstalled it I can still not reproduce it.

**Comment by Werder630** [comment] 2020-08-17 14:58
yes, i haven't local changes too. For exmaple,  if i change `android:transitionName="@{@string/email_card_transition_name(email.id)}"` to `android:transitionName="@string/email_card_transition_name"` - app works awesome (but the animation not entirely accurate), so i consider, the problem due to dataBinding
PS: i try on AS 4.1 and 4.2

**Comment by dsn5ft** [comment] 2020-08-17 15:23
Thanks for confirming. Random guess, but can you try doing a `Build > Clean Project` and then a `Build > Rebuild Project` in Android Studio, and then running the app without using Instant Run?

**Comment by Werder630** [comment] 2020-08-17 15:24
It is strange, when i rebuilt app several times, the crash disappeared...  @dsn5ft Could you clone app from scratch, and try launch app on branch complete?

**Comment by IgnacioGarcia198** [comment] 2020-08-17 15:45
I cloned app as new project again and run complete branch. Not happening anymore. I also tried wiping app data, cleaning project, installing again. Not reproducing at all.

**Comment by Werder630** [comment] 2020-08-17 15:48
Yes, it is strange floating bug, so i advise to close it

**Comment by dsn5ft** [comment] 2020-08-17 15:51
Same here, I wonder if it has to do with Studio caching an older version of the Gradle/AGP, and then the build gets into a bad state. I did recently update the repo's Gradle versions in https://github.com/material-components/material-components-android-motion-codelab/commit/d1d87ee3c4cf329d0ccbaba7ff59c10879b63a18, not sure if you originally cloned before that and then pulled. Anyway, closing for now but feel free to reopen if you find out more.

**Closed by dsn5ft** 2020-08-17 15:51 UTC

**Comment by ecexplorer** [comment] 2020-09-29 20:13
I just experienced this going through the codelab fresh.
`AS 4.0.1`

Coming in from building a project previously that uses...
```distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
classpath 'com.android.tools.build:gradle:3.6.4'```

Doing a project clean _seems_ to resolve the issue.

**Comment by maurobanze** [comment] 2020-10-03 17:56
Ran into the same issue as well on `Android Studio 4.0.1`. Cleaning and rebuilding the project as suggested fixed the issue.

**Comment by ELTEGANI** [comment] 2020-12-11 16:23
> @Werder630 @IgnacioGarcia198 thanks for trying out the codelab!
> 
> When I check out the `complete` branch, run the app, and click on an email, the transition runs successfully and I don't see the crash. Same thing happens if I start from `develop` and add in the transition names, the navigate call with `FragmentNavigatorExtras`, and the `MaterialContainerTransform` `sharedElementEnterTransition`.
> 
> Can you make sure that the `android:transitionName="@{@string/email_card_transition_name(email.id)}"` is set on the `MaterialCardView` in `email_item_layout.xml`, as opposed to the `MaterialCardView` in `fragment_email.xml`? That's the important part for ensuring uniqueness.
> 
> Also, if you can fork the codelab repo and push your local changes to a branch, I can take a look to see if there's an issue.

exactly as mentioned, it was in constraint layout it supposes to be in cardview. all-star :)
